version: "3.8"

services:
  redis:
    container_name: sso-redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 64M
    networks:
      - sso-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sso
      MONGO_INITDB_ROOT_PASSWORD: sso
    volumes:
      - ./docker/db/mongodb/data:/data/db
    restart: always
    networks:
      - sso-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sso
      ME_CONFIG_MONGODB_ADMINPASSWORD: sso
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    restart: always
    networks:
      - sso-network

volumes:
  sso-data:
    driver: local

networks:
  sso-network:
    driver: bridge
