version: "3.8"

services:
  redis:
    container_name: sso-redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 64M
    networks:
      - cassandra-network
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042" # Expose Cassandra's default port (CQL)
    environment:
      - CASSANDRA_CLUSTER_NAME=sso
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_LISTENER_INTERFACE=eth0
      - CASSANDRA_LISTENER_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZATION=CassandraAuthorizer
      - CASSANDRA_PASSWORD="sso"
      - CASSANDRA_USER="sso"
    volumes:
      - ./docker/db/cassandra/data:/var/lib/cassandra
    networks:
      - cassandra-network

  # Optional: a client to interact with Cassandra, like cqlsh
  cqlsh:
    image: cassandra:3.11
    container_name: cqlsh
    command: cqlsh cassandra 9042
    depends_on:
      - cassandra
    networks:
      - cassandra-network

volumes:
  cassandra-data:
    driver: local

networks:
  cassandra-network:
    driver: bridge
